INSERT INTO category (code, name, icon, type, is_default, sort_order)
VALUES
    ('food', '餐饮', 'food', 'expense', TRUE, 10),
    ('transport', '交通', 'transport', 'expense', TRUE, 20),
    ('shopping', '购物', 'shopping', 'expense', TRUE, 30),
    ('fruit', '水果', 'fruit', 'expense', TRUE, 40),
    ('snack', '零食', 'snack', 'expense', TRUE, 50),
    ('housing', '住房', 'housing', 'expense', TRUE, 60),
    ('fun', '娱乐', 'fun', 'expense', TRUE, 70),
    ('med', '医疗', 'med', 'expense', TRUE, 80),
    ('edu', '教育', 'edu', 'expense', TRUE, 90),
    ('tel', '通讯', 'tel', 'expense', TRUE, 100),
    ('cloth', '服饰', 'cloth', 'expense', TRUE, 110),
    ('beauty', '美容', 'beauty', 'expense', TRUE, 120),
    ('social', '人情', 'social', 'expense', TRUE, 130),
    ('travel', '旅行', 'travel', 'expense', TRUE, 140),
    ('other', '其他', 'other', 'expense', TRUE, 150),
    ('salary', '工资', 'salary', 'income', TRUE, 210),
    ('bonus', '奖金', 'bonus', 'income', TRUE, 220),
    ('invest', '理财', 'invest', 'income', TRUE, 230),
    ('part', '兼职', 'part', 'income', TRUE, 240),
    ('red', '红包', 'red', 'income', TRUE, 250),
    ('refund', '退款', 'refund', 'income', TRUE, 260),
    ('otherin', '其他', 'otherin', 'income', TRUE, 270);
